rules = {
  "one": "引いた人以外が飲む。",
  "two": "引いた人が一人を指名して飲む。",
  "three": "引いた人が飲む。",
  "four": "女性が全員飲む。",
  "five": "引いた人の左右の人が飲む。",
  "six": "男性全員が飲む。",
  "seven": "山手線ゲームをして負けた人が飲む。",
  "eight": "一蓮托生",
  "nine": "引いた人が他の好きなゲームを決める。負けた人が飲む。",
  "ten": "山手線ゲームをして負けた人が飲む。",
  "eleven": "これを引いた人は好きなルール（例：カタカナ禁止など）を作る。そのルールを破ったら飲む。",
  "twelve": "引いた人は”クエスチョンマスター”となり、周りの人はクエスチョンマスターがした質問には答えてはいけない。答えてしまった人は飲む。",
  "king": "引いた人が一人を指名して飲む。"
}

cards = [
  { "url": "./img/torannpu-illust1.png", "exp": rules.one },
  { "url": "./img/torannpu-illust2.png", "exp": rules.two },
  { "url": "./img/torannpu-illust3.png", "exp": rules.three },
  { "url": "./img/torannpu-illust4.png", "exp": rules.four },
  { "url": "./img/torannpu-illust5.png", "exp": rules.five },
  { "url": "./img/torannpu-illust6.png", "exp": rules.six },
  { "url": "./img/torannpu-illust7.png", "exp": rules.seven },
  { "url": "./img/torannpu-illust8.png", "exp": rules.eight },
  { "url": "./img/torannpu-illust9.png", "exp": rules.nine },
  { "url": "./img/torannpu-illust10.png", "exp": rules.ten },
  { "url": "./img/torannpu-illust11.png", "exp": rules.eleven },
  { "url": "./img/torannpu-illust12.png", "exp": rules.twelve },
  { "url": "./img/torannpu-illust13.png", "exp": rules.king },
  { "url": "./img/torannpu-illust14.png", "exp": rules.one },
  { "url": "./img/torannpu-illust15.png", "exp": rules.two },
  { "url": "./img/torannpu-illust16.png", "exp": rules.three },
  { "url": "./img/torannpu-illust17.png", "exp": rules.four },
  { "url": "./img/torannpu-illust18.png", "exp": rules.five },
  { "url": "./img/torannpu-illust19.png", "exp": rules.six },
  { "url": "./img/torannpu-illust20.png", "exp": rules.seven },
  { "url": "./img/torannpu-illust21.png", "exp": rules.eight },
  { "url": "./img/torannpu-illust22.png", "exp": rules.nine },
  { "url": "./img/torannpu-illust23.png", "exp": rules.ten },
  { "url": "./img/torannpu-illust24.png", "exp": rules.eleven },
  { "url": "./img/torannpu-illust25.png", "exp": rules.twelve },
  { "url": "./img/torannpu-illust26.png", "exp": rules.king },
  { "url": "./img/torannpu-illust27.png", "exp": rules.one },
  { "url": "./img/torannpu-illust28.png", "exp": rules.two },
  { "url": "./img/torannpu-illust29.png", "exp": rules.three },
  { "url": "./img/torannpu-illust30.png", "exp": rules.four },
  { "url": "./img/torannpu-illust31.png", "exp": rules.five },
  { "url": "./img/torannpu-illust32.png", "exp": rules.six },
  { "url": "./img/torannpu-illust33.png", "exp": rules.seven },
  { "url": "./img/torannpu-illust34.png", "exp": rules.eight },
  { "url": "./img/torannpu-illust35.png", "exp": rules.nine },
  { "url": "./img/torannpu-illust36.png", "exp": rules.ten },
  { "url": "./img/torannpu-illust37.png", "exp": rules.eleven },
  { "url": "./img/torannpu-illust38.png", "exp": rules.twelve },
  { "url": "./img/torannpu-illust39.png", "exp": rules.king },
  { "url": "./img/torannpu-illust40.png", "exp": rules.one },
  { "url": "./img/torannpu-illust41.png", "exp": rules.two },
  { "url": "./img/torannpu-illust42.png", "exp": rules.three },
  { "url": "./img/torannpu-illust43.png", "exp": rules.four },
  { "url": "./img/torannpu-illust44.png", "exp": rules.five },
  { "url": "./img/torannpu-illust45.png", "exp": rules.six },
  { "url": "./img/torannpu-illust46.png", "exp": rules.seven },
  { "url": "./img/torannpu-illust47.png", "exp": rules.eight },
  { "url": "./img/torannpu-illust48.png", "exp": rules.nine },
  { "url": "./img/torannpu-illust49.png", "exp": rules.ten },
  { "url": "./img/torannpu-illust50.png", "exp": rules.eleven },
  { "url": "./img/torannpu-illust51.png", "exp": rules.twelve },
  { "url": "./img/torannpu-illust52.png", "exp": rules.king }
]